package com.zhanglinwei.zTools.common.constants;

public interface SpringPool {

    String AMPERSAND = "&";
    String AND = "and";
    String AT = "@";
    String ASTERISK = "*";
    String STAR = ASTERISK;
    String STAR_STAR = "**";
    String DOT_STAR = ".*";
    String BACK_SLASH = "\\";
    String COLON = ":";
    String COMMA = ",";
    String COMMA_SPACE = ", ";
    String DASH = "-";
    String DOLLAR = "$";
    String DUN = "、";
    String DOT = ".";
    String DOT_DOT = "..";
    String DOT_CLASS = ".class";
    String DOT_JAVA = ".java";
    String DOT_XML = ".xml";
    String EMPTY = "";
    String EQUAL = "=";
    String EQUALS = "==";
    String FALSE = "false";
    String SLASH = "/";
    String DOUBLE_SLASH = "//";
    String SPACE_SLASH_SLASH_SPACE = " // ";
    String HASH = "#";
    String HAT = "^";
    String LEFT_BRACE = "{";
    String LEFT_BRACKET = "(";
    String LEFT_CHEV = "<";
    String DOT_NEWLINE = ",\n";
    String NEWLINE = "\n";
    String n = "n";
    String N = "N";
    String NO = "no";
    String NULL = "null";
    String NA = "N/A";
    String NUM = "NUM";
    String OFF = "off";
    String ON = "on";
    String PERCENT = "%";
    String PIPE = "|";
    String PLUS = "+";
    String QUESTION_MARK = "?";
    String EXCLAMATION_MARK = "!";
    String QUOTE = "\"";
    String RETURN = "\r";
    String TAB = "\t";
    String FOLD = "└";
    String RIGHT_BRACE = "}";
    String RIGHT_BRACKET = ")";
    String RIGHT_CHEV = ">";
    String SEMICOLON = ";";
    String SINGLE_QUOTE = "'";
    String BACKTICK = "`";
    String SPACE = " ";
    String SQL = "sql";
    String TILDA = "~";
    String LEFT_SQ_BRACKET = "[";
    String RIGHT_SQ_BRACKET = "]";
    String TRUE = "true";
    String UNDERSCORE = "_";
    String UTF_8 = "UTF-8";
    String US_ASCII = "US-ASCII";
    String ISO_8859_1 = "ISO-8859-1";
    String y = "y";
    String Y = "Y";
    String YES = "yes";
    String ONE = "1";
    String ZERO = "0";
    String DOLLAR_LEFT_BRACE = "${";
    String HASH_LEFT_BRACE = "#{";
    String CRLF = "\r\n";

    String HTML_NBSP = "&nbsp;";
    String HTML_AMP = "&amp";
    String HTML_QUOTE = "&quot;";
    String HTML_LT = "&lt;";
    String HTML_GT = "&gt;";
    String SCRIPT_OPEN = "<script>";
    String SCRIPT_CLOSE = "</script>";

}
